name: Publish
on:
  push:
jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-node@v6
          with:
            node-version: 24
        - run: |
            npm ci
            npm run build
            cp -r .vitepress/dist public
        - uses: actions/git-pages@v2
          with:
            site: https://xiaoshihou.codeberg.page/
            token: ${{ secrets.GIT_PAGES_TOKEN }}
            source: public
