name: Publish
on:
  push:
jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: |
          npm ci
          npm run build
      - uses: actions/git-pages@v2
        with:
          site: https://xiaoshihou.codeberg.page/
          token: ${{ forge.token }}
          source: .vitepress/dist
